sudo: true

language: c

branches:
  except: /^(gh-pages|v[0-9]\..*)/

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - xserver-xorg-dev
      - nasm
      - gcc-multilib

env:
  global:
    - XRDP_CFLAGS=-I$(pwd)/xrdp/common
  matrix:
    - CONF_FLAGS="" DISTCHECK=1
    - CONF_FLAGS="--without-simd"
    - CONF_FLAGS="--host=i686-linux" CFLAGS=-m32 XFAIL_TESTS=xorg-test-run.sh

install:
  - git clone --depth 1 --branch=devel https://github.com/neutrinolabs/xrdp.git xrdp

script:
  - ./bootstrap
  - ./configure $CONF_FLAGS
  - make CFLAGS="$CFLAGS -O2 -Wall -Wwrite-strings -Werror"
  - make check
  - test -z "$DISTCHECK" || make distcheck
  - sudo apt-get install git autoconf libtool pkg-config gcc g++ make  libssl-dev libpam0g-dev libjpeg-dev libx11-dev libxfixes-dev libxrandr-dev  flex bison libxml2-dev intltool xsltproc xutils-dev python-libxml2 g++ xutils libfuse-dev libmp3lame-dev nasm libpixman-1-dev xserver-xorg-dev checkinstall -y
  - ./bootstrap
  - ./configure
  - make
  - sudo checkinstall --install=no -y 
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh *.deb

after_script:
 - for f in tests/*.log; do echo $f; cat -n $f; done
