sudo: false

language: c

branches:
  except: /^(gh-pages|v[0-9]\..*)/

compiler:
  - clang
  - gcc

addons:
  apt:
    packages:
      - xserver-xorg-dev
      - nasm
      - gcc-multilib

env:
  global:
    - PKG_CONFIG_PATH=`pwd`/xrdp/pkgconfig
  matrix:
    - CONF_FLAGS="" DISTCHECK=1
    - CONF_FLAGS="--without-simd"
    - CONF_FLAGS="--host=i686-linux" CFLAGS=-m32 LDFLAGS=-m32 XFAIL_TESTS=xorg-test-run.sh

install:
  - git clone --depth 1 --branch=devel https://github.com/neutrinolabs/xrdp.git xrdp
    && sed -e 's/@VERSION@/0.9.0/g' -e "s,@abs_top_srcdir@,`pwd`/xrdp,g" xrdp/pkgconfig/xrdp-uninstalled.pc.in >xrdp/pkgconfig/xrdp-uninstalled.pc

script:
  - ./bootstrap
  - ./configure $CONF_FLAGS
  - make CFLAGS="$CFLAGS -O2 -Wall -Wwrite-strings -Werror"
  - make check
  - test -z "$DISTCHECK" || make distcheck
